language: c
sudo: false

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install md5sha1sum; fi
  - source devtools/travis-ci/install.sh
  - conda config --add channels omnia

script:
  - conda build devtools/conda-recipe
os:
  - osx
  - linux

env:
  matrix:
    - python=2.7  CONDA_PY=27
    - python=3.4  CONDA_PY=34
    - python=3.5  CONDA_PY=35

  global:
    # BINSTAR
    - secure: "UGmEljhTf6mQxjhj6We2PPNaNsaYONoFgH30SEofJDNIqXSM6zNQzSVOm5RBxfvVdw+TSYwmyZ/XmMio+yIWMDBXXW8MbGHWYIGqevSkgqCT9qqZv2475MCyPFpmyucQzN+0/3+b7JxAR/VC2N6CLPGohsUe1Up/xU3MfY5DcJY="


